version: '3.6'
services:
  krisha_mock_api:
    container_name: krisha_mock_api
    restart: always
    build: .
    networks:
      - dc-net
#    environment:
      #CONFIG SERVER
#      CONFIG_SERVER_URL: http://config_server
#      SERVICE_NAME: krisha
#      NAMESPACE: dev-dc
#      M_TOKEN: ${M_TOKEN}
      #END CONFIG SERVER
    ports:
      - 84:8084
networks:
  dc-net:
    external: true